# Generated by Django 5.2.10 on 2026-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_is_anonymous_alter_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
