# Generated by Django 5.2.10 on 2026-03-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_similarity_score_alter_complaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
