# Generated by Django 5.2.10 on 2026-03-31 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='admin_comments',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='hod_comments',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='similarity_score',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready for Assignment', 'Ready for Assignment'), ('In Progress', 'In Progress'), ('Solved', 'Solved'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
