# Generated by Django 5.2.13 on 2026-04-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_remove_complaint_admin_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
    ]
