# Generated by Django 5.2.10 on 2026-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('HOD', 'HOD'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
